- name: Create folder for Docker files
  ansible.builtin.file:
    path: /opt/cloud1
    state: directory
    mode: "0755"

- name: Create Caddy directory
  ansible.builtin.file:
    path: /opt/cloud1/caddy
    state: directory
    mode: "0755"

- name: Deploy docker-compose.yml
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: /opt/cloud1/docker-compose.yml
    mode: "0600"

- name: Deploy Caddyfile
  ansible.builtin.template:
    src: Caddyfile.j2
    dest: /opt/cloud1/caddy/Caddyfile
    mode: "0644"

- name: Start Cloud-1 Docker Compose stack
  community.docker.docker_compose_v2:
    project_src: /opt/cloud1
    state: present
    remove_orphans: true

- name: Check whether WordPress is installed
  ansible.builtin.command:
    cmd: >
      docker compose run --rm wpcli
      wp core is-installed
    chdir: /opt/cloud1
  register: wordpress_installed
  changed_when: false
  failed_when: wordpress_installed.rc not in [0, 1]

- name: Install WordPress
  ansible.builtin.command:
    argv:
      - docker
      - compose
      - run
      - --rm
      - wpcli
      - wp
      - core
      - install
      - "--url=https://{{ domain_name }}"
      - "--title={{ wordpress_title }}"
      - "--admin_user={{ wordpress_admin_user }}"
      - "--admin_password={{ vault_wordpress_admin_password }}"
      - "--admin_email={{ wordpress_admin_email }}"
      - --skip-email
    chdir: /opt/cloud1
  when: wordpress_installed.rc == 1
  no_log: true