- name: Install ufw
  ansible.builtin.apt:
    name: ufw
    state: present

- name: Allow SSH (port 22)
  community.general.ufw:
    rule: allow
    port: "22"
    proto: tcp

- name: Allow HTTP (port 80)
  community.general.ufw:
    rule: allow
    port: "80"
    proto: tcp

- name: Allow HTTPS (port 443)
  community.general.ufw:
    rule: allow
    port: "443"
    proto: tcp

- name: Turn on firewall
  community.general.ufw:
    state: enabled
    policy: deny
    